comment and reorganize create-user

diff --git a/project-2/create-user b/project-2/create-user
--- a/project-2/create-user
+++ b/project-2/create-user
@@ -28,21 +28,57 @@ check_name () {
   #   dashes not at the beginning 
   #   $ only at the end
   #   Max length of 32 chars
-  # NOTE: while characteerse like $ and - are allowed in certain scenarios, they must be escaped when passed as an argument
+  # NOTE: while characters like $ and - are allowed in certain scenarios, they must be escaped when passed as an argument
 	#				Not esacping these characters will result in parsing errors.
 	name=$1
+	while getopts ":gu" opts; do
+    case $opts in
+      g)  # GID
+        file="/etc/group"
+        ;;
+      u)  # UID
+        file="/etc/passwd"
+        ;;
+      *)
+        echo "$0: $FUNCNAME: Syntax: get_next_ID [-g|-u]"
+        echo "-g: GID  -u: UID"
+        exit 1
+        ;;
+    esac
+  done
+
+	# Regex explainations
+	#		[^A-Za-z0-9_\\$\\-]+	: match name if it contains a character not in this list (Alnum, $, _, -)
+	#		^[0-9]+$							: match name if it is a number (contains >=1 digits and no other chars)
+	#		^-										: match name if it starts with a dash
+	#		\\$.+									:	match name if it contains a $ followed by another character ($ is not at end of name)
   declare -a regex_arr=("[^A-Za-z0-9_\\$\\-]+" "^[0-9]+$" "^-" "\\$.+")
 
+	# using return instead of echo here because the function needs to end when it matches a condition
+	
+	# name length check
+	# ${$<VARNAME>} gets the length of the variable
   if [[ ${#name} -gt 32 ]]; then
+		echo "$0: Name must be 32 characters or less: $name"
 		return 1
   fi
 
+	# testing the name against regex
   for regex in ${regex_arr[@]}; do
     result=$(echo $name | grep -iE $regex)
 		if [[ -n $result ]]; then
+			echo "$0: Invalid name: $name"
 			return 1
     fi
   done
+
+	# check if name is taken
+	# matching the first field by wrapping the username in ^ (start of line) and : (delimiter of files)
+	if [[ -n $(echo $file | grep -iE "^$username:") ]]; then
+		echo "$0: Name has been taken in $file: $username"
+		exit 1
+	fi
+
   return 0
 }
 
@@ -68,16 +104,18 @@ get_next_ID () {
   echo "$(($(grep -Ev ":[0-9]{1,3}:|:6553[3-4]:" $file | cut -d ":" -f 3 | sort -gr | head -n 1)+1))"
 }
 
+# default shell to give users
 shell=/usr/bin/bash
 
 while getopts ":hs:g:" opts; do
   case $opts in
     s)
+			# Change what shell to give the user
       # This only checks if it's executable, doesn't check if it's a valid shell program
       if [[ -x $OPTARG ]]; then
         shell=$OPTARG
       elif [[ -n $OPTARG ]]; then
-        echo "[Error] $OPTARG is not an executable"
+        echo "$0: $OPTARG is not an executable"
         exit 1
       fi
       ;;
@@ -88,8 +126,7 @@ while getopts ":hs:g:" opts; do
       for groupname in $aux_groups[@];do
 				check_name $groupname
 				if [[ $? -eq 1 ]];then
-					echo "$0: Invalid group name: $groupname"
-					exit 1 # maybe?
+					exit 1
 				fi
 			done
 			;;
@@ -99,32 +136,30 @@ while getopts ":hs:g:" opts; do
       exit 0
       ;;
   esac
-done
+donei
 
 # shift flags to get arguments
 shift $(($OPTIND-1))
 username=$1
 
+# checking if username meets standards and is available
 check_name $username
 if [[ $? -eq 1 ]];then
-	echo "$0: Invalid user name: $username"
-	exit 1 #maybe?
-elif [[ -n $(echo /etc/passwd | grep -iE "^$username:") ]]; then
-	echo "$0: Username has been taken: $username"
 	exit 1
 fi
+
 
 uid=$(get_next_ID -u)
 # Check if UID is an available GID
 # If not, get the next availalbe GID
-search_result=$(grep $uid /etc/group)
-if [[ -n $search_result ]];then
+if [[ -n $(grep $uid /etc/group) ]];then
   primary_gid=$(get_next_ID -g)
 else
   primary_gid=$uid
 fi
 
 # Adding user to /etc/passwd
+# >> to append to file instead of overwrite
 home_dir="/home/$username"
 cat >> /etc/passwd <<- EOF
 	$username:x:$uid:$primary_gid::$home_dir:$shell
@@ -132,32 +167,49 @@ EOF
 
 # Creating user's home dir
 if [[ -d $home_dir ]];then
+	# if the directory already exists, only copy /etc/skel into if -f was passed as an option
 	echo $home_dir already exists.
 	if [[ force = false ]];then
 		echo Not copying /etc/skel into directory.
 	else
 		echo Copying /etc/skel into direcotry.
-		cp -r /etc/skel $home_dir
+		cp -r /etc/skel/. $home_dir
 	fi
 else
+	echo "Creating $home_dir"
 	mkdir $home_dir
 	cp -r /etc/skel/. $home_dir
 fi
+# make directory rwx by owner only
+# reference: I looked at the other home directories
 chmod 700 $home_dir
+# transfer user and group ownership to new user and their primary group 
 chown "$username:$username" $home_dir
 
 # Adding primary group to /etc/group
+# >> to append to file instead of overwrite
 cat >> /etc/group <<- EOF
 	$username:x:$primary_gid:
 EOF
 
-
 # Adding additional groups to /etc/group
+# I heard from someone that you don't need to do this but I already made it
+# Only if the instructions were more specific on the requirements
 if [[ -n $group ]]; then
   for groupname in $groups[@]; do
+		# Check if group exists
     group_search=$(grep -iE "^$groupname:" /etc/group)
     if [[ -n $group_search ]];then
+			# Check if group has members
       current_members=$(echo $group_search | cut -d ":" -f 4)
+			# sed explanation:
+			#		first field is the input string
+			#		2nd field (s) tells sed to subsitute something in the input
+			#		3rd field is the target for subsitution
+			#			$ represents the end of the string
+			#		4th field is the string to subsitute with
+			# reference: https://www.gnu.org/software/sed/manual/sed.html#sed-script-overview
+			# & https://www.gnu.org/software/sed/manual/sed.html#sed-commands-summary
       if [[ -n current_members ]]; then
         sed "/$group_search/s/$/$current_members,$username/" /etc/group
       else
@@ -171,4 +223,3 @@ if [[ -n $group ]]; then
     fi
   done
 fi
-
